Uso de SQLite3 en python

In [7]:
import sqlite3
import pandas as pd

In [8]:
conexion=sqlite3.connect("dbprueba.db") #Conecta con la DB o crea una

In [9]:
df = pd.read_csv("Laboratorio de Prueba - Inventario.csv") #Lee el csv y lo carga como dataframe

In [10]:
cur = conexion.cursor() #Abre el cursor
df.to_sql('LaboPrueba', conexion, if_exists='append', index=False) #Crea la tabla con los datos del DF
cur.close() #Cierra el cursor

In [11]:
def consulta_general(nombre=None, descripcion =None, tipo=None, modelo=None, marca=None, estado=None, serie=None): #Funcion para hacer consultas en la Base de Datos
    cursor = conexion.cursor()

    # Construcción del query SELECT
    query = "SELECT DISTINCT * FROM 'LaboPrueba'"
    condiciones = []
    parametros = []


    if descripcion is not None:
        condiciones.append('"Descripción y Observaciones" LIKE ?')
        parametros.append('%' + descripcion + '%')
    if nombre is not None:
        condiciones.append("nombre LIKE ?")
        parametros.append('%' + nombre + '%')
    if tipo is not None:
        condiciones.append("tipo = ?")
        parametros.append(tipo)
    if modelo is not None:
        condiciones.append("modelo = ?")
        parametros.append(modelo)
    if marca is not None:
        condiciones.append("marca = ?")
        parametros.append(marca)
    if estado is not None:
        condiciones.append("estado = ?")
        parametros.append(estado)
    if serie is not None:
        condiciones.append("serie = ?")
        parametros.append(serie)

    if condiciones:
        query += " WHERE " + " AND ".join(condiciones)

    # Ejecución de la consulta
    cursor.execute(query, parametros)
    resultados = cursor.fetchall()

    # Cierre de la conexión y retorno de resultados
    cursor.close()
    return pd.DataFrame(resultados, columns=df.columns)

In [12]:
consulta_general(nombre='pasco')

,id,Tipo,Nro.,Nombre,Descripción y Observaciones,Marca,Modelo,Serie,Mueble,Lugar,Estado
0,30027,B,1,Bobina Pasco,Bobina primaria y secundaria,Vernier-Pasco,SE-8653,None,IV,B,OK
1,30028,B,2,Bobina Pasco,Bobina primaria y secundaria,Vernier-Pasco,SE-8653,None,IV,B,OK
2,30029,B,3,Bobina Pasco,Bobina primaria y secundaria,Vernier-Pasco,SE-8653,None,IV,B,OK
3,30030,B,4,Bobina Pasco,Bobina primaria y secundaria,Vernier-Pasco,SE-8653,None,IV,B,OK
4,30031,B,5,Bobina Pasco,Bobina primaria y secundaria,Vernier-Pasco,SE-8653,None,IV,B,OK
5,30032,B,6,Bobina Pasco,Bobina primaria y secundaria,Vernier-Pasco,SE-8653,None,IV,B,Prestado
6,30033,B,7,Bobina Pasco,Bobina primaria y secundaria,Vernier-Pasco,SE-8653,None,IV,B,OK
7,30041,BT,1,Transformadores Pasco,Juego de bobinas y núcleos para transformador ...,Pasco,SF-8617,None,IV,C,OK
8,30042,BT,2,Transformadores Pasco,Juego de bobinas y núcleos para transformador ...,Pasco,SF-8617,None,IV,C,Reparacion
9,30043,BT,3,Transformadores Pasco,Juego de bobinas y núcleos para transformador ...,Pasco,SF-8617,None,IV,C,OK
10,30044,BT,4,Transformadores Pasco,Juego de bobinas y núcleos para transformador ...,Pasco,SF-8617,None,IV,C,OK
11,30045,I,1,Iman Pasco,Iman Pasco,Pasco,EM-8641,None,IV,C,OK
12,30046,I,2,Iman Pasco,Iman Pasco,Pasco,EM-8641,None,IV,C,OK
13,30047,I,3,Iman Pasco,Iman Pasco,Pasco,EM-8641,None,IV,C,OK
14,30048,I,4,Iman Pasco,Iman Pasco,Pasco,EM-8641,None,IV,C,Reparacion

Ahora se puede buscar por cada columna o varias simultaneamente. Tambien en nombre